//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nexteNews2.nextenews1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceDBSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceDB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddpostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginNotifyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceDB() {
            this.Url = "http://testnexte-001-site1.gtempurl.com/android/WebServiceDB.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddpostCompletedEventHandler AddpostCompleted;
        
        /// <remarks/>
        public event GetAllDataCompletedEventHandler GetAllDataCompleted;
        
        /// <remarks/>
        public event LoginNotifyCompletedEventHandler LoginNotifyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Addpost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnData Addpost(string Title, string Author, string URL, string Content, string Email, string img) {
            object[] results = this.Invoke("Addpost", new object[] {
                        Title,
                        Author,
                        URL,
                        Content,
                        Email,
                        img});
            return ((ReturnData)(results[0]));
        }
        
        /// <remarks/>
        public void AddpostAsync(string Title, string Author, string URL, string Content, string Email, string img) {
            this.AddpostAsync(Title, Author, URL, Content, Email, img, null);
        }
        
        /// <remarks/>
        public void AddpostAsync(string Title, string Author, string URL, string Content, string Email, string img, object userState) {
            if ((this.AddpostOperationCompleted == null)) {
                this.AddpostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddpostOperationCompleted);
            }
            this.InvokeAsync("Addpost", new object[] {
                        Title,
                        Author,
                        URL,
                        Content,
                        Email,
                        img}, this.AddpostOperationCompleted, userState);
        }
        
        private void OnAddpostOperationCompleted(object arg) {
            if ((this.AddpostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddpostCompleted(this, new AddpostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnData2[] GetAllData() {
            object[] results = this.Invoke("GetAllData", new object[0]);
            return ((ReturnData2[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDataAsync() {
            this.GetAllDataAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDataAsync(object userState) {
            if ((this.GetAllDataOperationCompleted == null)) {
                this.GetAllDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDataOperationCompleted);
            }
            this.InvokeAsync("GetAllData", new object[0], this.GetAllDataOperationCompleted, userState);
        }
        
        private void OnGetAllDataOperationCompleted(object arg) {
            if ((this.GetAllDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDataCompleted(this, new GetAllDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginNotify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnData LoginNotify(int UserID) {
            object[] results = this.Invoke("LoginNotify", new object[] {
                        UserID});
            return ((ReturnData)(results[0]));
        }
        
        /// <remarks/>
        public void LoginNotifyAsync(int UserID) {
            this.LoginNotifyAsync(UserID, null);
        }
        
        /// <remarks/>
        public void LoginNotifyAsync(int UserID, object userState) {
            if ((this.LoginNotifyOperationCompleted == null)) {
                this.LoginNotifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginNotifyOperationCompleted);
            }
            this.InvokeAsync("LoginNotify", new object[] {
                        UserID}, this.LoginNotifyOperationCompleted, userState);
        }
        
        private void OnLoginNotifyOperationCompleted(object arg) {
            if ((this.LoginNotifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginNotifyCompleted(this, new LoginNotifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnData {
        
        private string messageField;
        
        private int postIDField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int PostID {
            get {
                return this.postIDField;
            }
            set {
                this.postIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnData2 {
        
        private string titleField;
        
        private string authorField;
        
        private string uRLField;
        
        private string contentField;
        
        private string emailField;
        
        private string imgField;
        
        private System.DateTime dateField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddpostCompletedEventHandler(object sender, AddpostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddpostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddpostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllDataCompletedEventHandler(object sender, GetAllDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnData2[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnData2[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void LoginNotifyCompletedEventHandler(object sender, LoginNotifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginNotifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginNotifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591