#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nexteNews2.Resource", IsApplication=true)]

namespace nexteNews2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040010
			public const int black = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int black_overlay = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int customeblue = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int darkblue = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int darkgreen = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int darkorange = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int darkpurple = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int darkred = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int lowDarkfont = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int orange = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int purple = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int red = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int white = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int whiteback = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int whitebackground = 2130968591;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addico = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int WhileBackground = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090007
			public const int Addnewpost = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int Authortext = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int ImageAdd = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int TitleText = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int Urltext = 2131296260;
			
			// aapt resource value: 0x7f090011
			public const int addnews = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int buttonRadMore = 2131296271;
			
			// aapt resource value: 0x7f090006
			public const int contentText = 2131296262;
			
			// aapt resource value: 0x7f09000d
			public const int imageURL = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int linearLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int linearLayoutmain = 2131296264;
			
			// aapt resource value: 0x7f090010
			public const int listView1 = 2131296272;
			
			// aapt resource value: 0x7f09000a
			public const int relativeLayout1 = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int textAuthor = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int textContanit = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int textDate = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int textTitle = 2131296268;
			
			// aapt resource value: 0x7f090001
			public const int textView1 = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addnewslay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listviewLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyCustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
